FROM python:3.9
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
COPY static/. /app/static
COPY utils/. /app/utils
COPY templates/. /app/templates
COPY blueprints/. /app/blueprints
COPY sass/. /app/sass
COPY core/. /app/core
COPY app.py startup.py config.py /app/
COPY run_k8.sh /app
ENV FLASK_APP=app.py
ENV MICROBLOGPUB_POUSSETACHES_HOST=localhost:7991
ENV MICROBLOGPUB_MONGODB_HOST=localhost:27017
CMD ["./run_k8.sh"]
