
apiVersion: v1
kind: Service
metadata:
  name: microblogpub-service
spec:
  type: NodePort
  selector:
    app: microblogpub-dev
  ports:
  - port: 5005
    targetPort: 5005
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: microblogpub-dev
  spec:
    selector:
      matchLabels:
        app: microblogpub-dev
    template:
      metadata:
        labels:
          app: microblogpub-dev
      spec:
        containers:
        - name: microblogpub-dev
          image: ghcr.io/howaboutudance/microblogpub-dev
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 5005
          env:
            - name: MICROBLOGPUB_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: envvars
                  key: mongodb-host
            - name: MICROBLOGPUB_POUSSETACHES_HOST 
              valueFrom:
                configMapKeyRef:
                  name: envvars
                  key: poussetaches-host
            - name: MICROBLOGPUB_INTERNAL_HOST
              valueFrom:
                configMapKeyRef:
                  name: deployvars
                  key: internal-host
          volumeMounts:
            - mountPath: /app/config/me.yml
              name: server-config-microblogpub
              subPath: me.yml
        volumes:
          - name: server-config-microblogpub
            configMap:
              name: frontend-config
              items:
                - key: me.yml
                  path: me.yml
        imagePullSecrets:
        - name: registry-dockerconfigjson
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envvars
data:
  mongodb-host: mongo-service:27017
  poussetaches-host: http://poussetaches-service:7991
  flask-debug: "1"
  microblogpub-dev: "1"