
apiVersion: v1
kind: Service
metadata:
  name: microblogpub-service
spec:
  type: NodePort
  selector:
    app: microblogpub-dev
  ports:
  - port: 5005
    targetPort: 5005
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: microblogpub-dev
  spec:
    selector:
      matchLabels:
        app: microblogpub-dev
    template:
      metadata:
        labels:
          app: microblogpub-dev
      spec:
        containers:
        - name: microblogpub-dev
          image: #FIXME: pull in your own image
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 5005
          env:
            - name: MICROBLOGPUB_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: envvars
                  key: mongodb-host
            - name: MICROBLOGPUB_POUSSETACHES_HOST 
              value: "http://poussetaches:7991"
          volumeMounts:
            - mountPath: /app/config/me.yml
              name: server-config-microblogpub
              subPath: me.yml
        volumes:
          - name: server-config-microblogpub
            configMap:
              name: server-config
              items:
                - key: me.yml
                  path: me.yml
        imagePullSecrets:
        - name: gcr-json-key #FIXME if using GCR set key
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: server-config
  data:
    me.yml: |
      username: 
      name: 
      domain: 
      https: true
      summary: 
      icon_url: 
      pass: 
      sourcecode_url: 'https://github.com/howaboutudance/microblog.pub'
      favicon_url: '/static/favicon.png'
      #profile_metadata:
      #    name1: 'value'
      #    name2: 'value2'
      #hide_following: true
      #manually_approves_followers: false
      #aliases:
      #    - "http://example.com/users/name"
      #    - ...
      theme:
          style: "dark" #or "dark"
          color: "#33ff00"   # (purple, default for dark)